spring:
  application:
    name: pos-order
  # rabbitmq:
  #   host: localhost
  #   port: 15672
  #   username: guest
  #   password: guest
  # cloud:
  #   stream:
  #     function:
  #       autodetect: false
  #     bindings:
  #         order-out: 
  #           binder: rabbit
  #           destination: orderExchange
  #           group: default

server:
  port: 8085

# eureka:
#   client:
#     serviceUrl:
#       defaultZone: http://localhost:8761/eureka/
